# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0055_order_line_labels'),
        ('shuup_stripe', '0002_update_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_token', models.CharField(max_length=100, verbose_name='Stripe customer ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to='shuup.Contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
            },
        ),
    ]
