# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_stripe', '0003_saved_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecheckoutpaymentprocessor',
            name='publishable_key',
            field=models.CharField(max_length=255, verbose_name='Publishable Key'),
        ),
        migrations.AlterField(
            model_name='stripecheckoutpaymentprocessor',
            name='secret_key',
            field=models.CharField(max_length=255, verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='customer_token',
            field=models.CharField(max_length=255, verbose_name='Stripe customer ID'),
        ),
    ]
